<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Modules\Shipments\views\Images\quality_approval_stamp.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Styles\Controls\" />
    <Folder Include="Styles\Layout\" />
    <Folder Include="Styles\Tokens\" />
  </ItemGroup>


	<ItemGroup>
		<None Remove="appsettings.json" />
		<None Remove="appsettings.Development.json" />
		<None Remove="appsettings.Production.json" />

		<Content Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>

		<Content Include="appsettings.Development.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>

		<Content Include="appsettings.Production.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
	<PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Modules\Shipments\views\Images\quality_approval_stamp.png">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Resource>
  </ItemGroup>
	
	

</Project>
