"""add outsource purchase order tables

Revision ID: 81070df6e48c
Revises: 6b07fc7ca640
Create Date: 2026-04-20 15:49:00.214397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81070df6e48c'
down_revision: Union[str, Sequence[str], None] = '6b07fc7ca640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outsource_purchase_order",
        sa.Column("outsource_purchase_order_id", sa.BigInteger(), nullable=False),
        sa.Column("purchase_order_no", sa.String(length=40), nullable=False),
        sa.Column("purchase_order_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("process_type", sa.String(length=20), nullable=False),
        sa.Column("outsource_partner_id", sa.BigInteger(), nullable=False),
        sa.Column("inbound_partner_id", sa.BigInteger(), nullable=True),
        sa.Column("work_description", sa.Text(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("qty", sa.BigInteger(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("supply_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("vat_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "process_type IN ('CUT','PRINT')",
            name="ck_outsource_purchase_order__process_type",
        ),
        sa.CheckConstraint(
            "qty > 0",
            name="ck_outsource_purchase_order__qty_gt_0",
        ),
        sa.CheckConstraint(
            "supply_amount IS NULL OR supply_amount >= 0",
            name="ck_outsource_purchase_order__supply_amount_ge_0",
        ),
        sa.CheckConstraint(
            "total_amount IS NULL OR total_amount >= 0",
            name="ck_outsource_purchase_order__total_amount_ge_0",
        ),
        sa.CheckConstraint(
            "unit_price IS NULL OR unit_price >= 0",
            name="ck_outsource_purchase_order__unit_price_ge_0",
        ),
        sa.CheckConstraint(
            "vat_amount IS NULL OR vat_amount >= 0",
            name="ck_outsource_purchase_order__vat_amount_ge_0",
        ),
        sa.ForeignKeyConstraint(
            ["inbound_partner_id"],
            ["partner.partner_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["outsource_partner_id"],
            ["partner.partner_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("outsource_purchase_order_id"),
        sa.UniqueConstraint("purchase_order_no"),
    )
    op.create_index(
        "ix_outsource_purchase_order__inbound_partner_id",
        "outsource_purchase_order",
        ["inbound_partner_id"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order__outsource_partner_id",
        "outsource_purchase_order",
        ["outsource_partner_id"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order__process_type",
        "outsource_purchase_order",
        ["process_type"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order__purchase_order_date",
        "outsource_purchase_order",
        ["purchase_order_date"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order__purchase_order_no",
        "outsource_purchase_order",
        ["purchase_order_no"],
        unique=False,
    )

    op.create_table(
        "outsource_purchase_order_item",
        sa.Column("outsource_purchase_order_item_id", sa.BigInteger(), nullable=False),
        sa.Column("outsource_purchase_order_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("outsource_work_instruction_id", sa.BigInteger(), nullable=True),
        sa.Column("item_seq", sa.Integer(), nullable=False),
        sa.Column("qty", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("vendor_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("work_done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("work_done_qty", sa.BigInteger(), nullable=True),
        sa.Column("bad_qty", sa.BigInteger(), nullable=True),
        sa.Column("work_done_remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('VENDOR_RECEIVED','WORK_DONE','SHIPPED')",
            name="ck_outsource_purchase_order_item__status",
        ),
        sa.CheckConstraint(
            "bad_qty IS NULL OR bad_qty >= 0",
            name="ck_outsource_purchase_order_item__bad_qty_ge_0",
        ),
        sa.CheckConstraint(
            "qty > 0",
            name="ck_outsource_purchase_order_item__qty_gt_0",
        ),
        sa.CheckConstraint(
            "work_done_qty IS NULL OR work_done_qty >= 0",
            name="ck_outsource_purchase_order_item__work_done_qty_ge_0",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lot.lot_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["outsource_purchase_order_id"],
            ["outsource_purchase_order.outsource_purchase_order_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("outsource_purchase_order_item_id"),
    )
    op.create_index(
        "ix_outsource_purchase_order_item__lot_id",
        "outsource_purchase_order_item",
        ["lot_id"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order_item__purchase_order_id",
        "outsource_purchase_order_item",
        ["outsource_purchase_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_outsource_purchase_order_item__status",
        "outsource_purchase_order_item",
        ["status"],
        unique=False,
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outsource_purchase_order_item__status",
        table_name="outsource_purchase_order_item",
    )
    op.drop_index(
        "ix_outsource_purchase_order_item__purchase_order_id",
        table_name="outsource_purchase_order_item",
    )
    op.drop_index(
        "ix_outsource_purchase_order_item__lot_id",
        table_name="outsource_purchase_order_item",
    )
    op.drop_table("outsource_purchase_order_item")

    op.drop_index(
        "ix_outsource_purchase_order__purchase_order_no",
        table_name="outsource_purchase_order",
    )
    op.drop_index(
        "ix_outsource_purchase_order__purchase_order_date",
        table_name="outsource_purchase_order",
    )
    op.drop_index(
        "ix_outsource_purchase_order__process_type",
        table_name="outsource_purchase_order",
    )
    op.drop_index(
        "ix_outsource_purchase_order__outsource_partner_id",
        table_name="outsource_purchase_order",
    )
    op.drop_index(
        "ix_outsource_purchase_order__inbound_partner_id",
        table_name="outsource_purchase_order",
    )
    op.drop_table("outsource_purchase_order")
    # ### end Alembic commands ###
