"""initial schema

Revision ID: a7104deb3963
Revises: 
Create Date: 2026-04-28 14:43:36.666759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7104deb3963'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_type',
    sa.Column('defect_type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('defect_type_id')
    )
    op.create_index(op.f('ix_defect_type_code'), 'defect_type', ['code'], unique=True)
    op.create_index(op.f('ix_defect_type_name'), 'defect_type', ['name'], unique=False)
    op.create_table('drawing',
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('drawing_no', sa.String(length=60), nullable=False),
    sa.Column('current_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('drawing_id'),
    sa.UniqueConstraint('drawing_no', name='uq_drawing__drawing_no'),
    )
    op.create_index('ix_drawing__is_active', 'drawing', ['is_active'], unique=False)


    op.create_table(
    'drawing_revision',
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('rev_no', sa.String(length=20), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('drawing_id', 'rev_no', name='uq_drawing_revision__drawing_id__rev_no'),
    )
    op.create_index('ix_drawing_revision__drawing_id', 'drawing_revision', ['drawing_id'], unique=False)
    op.create_foreign_key(
    "fk_drawing__current_revision_id",
    "drawing",
    "drawing_revision",
    ["current_revision_id"],
    ["revision_id"],
    ondelete="SET NULL",
    )

    op.create_table('partner',
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('partner_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_no', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('business_no')
    )
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=False)
    op.create_table('process',
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_index(op.f('ix_process_process_code'), 'process', ['process_code'], unique=True)
    op.create_table('routing_template',
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('routing_template_id')
    )
    op.create_index(op.f('ix_routing_template_template_code'), 'routing_template', ['template_code'], unique=True)
    op.create_table('drawing_revision_file',
    sa.Column('revision_file_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('file_kind', sa.String(length=20), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['drawing_revision.revision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_file_id'),
    sa.UniqueConstraint('revision_id', 'file_kind', name='uq_drawing_revision_file__revision_id__file_kind')
    )
    op.create_index('ix_drawing_revision_file__file_kind', 'drawing_revision_file', ['file_kind'], unique=False)
    op.create_index('ix_drawing_revision_file__revision_id', 'drawing_revision_file', ['revision_id'], unique=False)
    op.create_table('outsource_purchase_order',
    sa.Column('outsource_purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_no', sa.String(length=40), nullable=False),
    sa.Column('purchase_order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('outsource_partner_id', sa.BigInteger(), nullable=False),
    sa.Column('inbound_partner_id', sa.BigInteger(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('form_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('supply_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type IN ('CUT','PRINT')", name='ck_outsource_purchase_order__process_type'),
    sa.CheckConstraint('qty > 0', name='ck_outsource_purchase_order__qty_gt_0'),
    sa.CheckConstraint('supply_amount IS NULL OR supply_amount >= 0', name='ck_outsource_purchase_order__supply_amount_ge_0'),
    sa.CheckConstraint('total_amount IS NULL OR total_amount >= 0', name='ck_outsource_purchase_order__total_amount_ge_0'),
    sa.CheckConstraint('unit_price IS NULL OR unit_price >= 0', name='ck_outsource_purchase_order__unit_price_ge_0'),
    sa.CheckConstraint('vat_amount IS NULL OR vat_amount >= 0', name='ck_outsource_purchase_order__vat_amount_ge_0'),
    sa.ForeignKeyConstraint(['inbound_partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outsource_partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outsource_purchase_order_id'),
    sa.UniqueConstraint('purchase_order_no')
    )
    op.create_index('ix_outsource_purchase_order__inbound_partner_id', 'outsource_purchase_order', ['inbound_partner_id'], unique=False)
    op.create_index('ix_outsource_purchase_order__outsource_partner_id', 'outsource_purchase_order', ['outsource_partner_id'], unique=False)
    op.create_index('ix_outsource_purchase_order__process_type', 'outsource_purchase_order', ['process_type'], unique=False)
    op.create_index('ix_outsource_purchase_order__purchase_order_date', 'outsource_purchase_order', ['purchase_order_date'], unique=False)
    op.create_index('ix_outsource_purchase_order__purchase_order_no', 'outsource_purchase_order', ['purchase_order_no'], unique=False)
    op.create_table('outsource_work_instruction',
    sa.Column('outsource_work_instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('instruction_no', sa.String(length=40), nullable=False),
    sa.Column('instruction_date', sa.Date(), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type IN ('CUT','PRINT')", name='ck_outsource_work_instruction__process_type'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outsource_work_instruction_id'),
    sa.UniqueConstraint('instruction_no')
    )
    op.create_index('ix_outsource_work_instruction__instruction_date', 'outsource_work_instruction', ['instruction_date'], unique=False)
    op.create_index('ix_outsource_work_instruction__partner_id', 'outsource_work_instruction', ['partner_id'], unique=False)
    op.create_index('ix_outsource_work_instruction__process_type', 'outsource_work_instruction', ['process_type'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=60), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('panel_width_mm', sa.Integer(), nullable=True),
    sa.Column('panel_length_mm', sa.Integer(), nullable=True),
    sa.Column('product_spec', sa.String(length=100), nullable=True),
    sa.Column('cut_qty_per_panel', sa.Integer(), nullable=True),
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('drawing_id', name='uq_product__drawing_id'),
    sa.UniqueConstraint('product_code', name='uq_product__product_code')
    )
    op.create_index('ix_product__is_active', 'product', ['is_active'], unique=False)
    op.create_table('routing_template_step',
    sa.Column('routing_template_step_id', sa.BigInteger(), nullable=False),
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('default_process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("default_process_type IN ('OUTSOURCE','INTERNAL')", name='ck_routing_template_step_default_process_type'),
    sa.CheckConstraint('step_seq > 0', name='ck_routing_template_step_seq_gt_0'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routing_template_step_id'),
    sa.UniqueConstraint('routing_template_id', 'step_seq', name='uq_routing_template_step_seq')
    )
    op.create_index(op.f('ix_routing_template_step_process_id'), 'routing_template_step', ['process_id'], unique=False)
    op.create_index(op.f('ix_routing_template_step_routing_template_id'), 'routing_template_step', ['routing_template_id'], unique=False)
    op.create_table('order_line',
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('customer_po', sa.String(length=60), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED','DONE','CANCELED')", name='ck_order_line__status_enum'),
    sa.CheckConstraint('line_no > 0', name='ck_order_line__line_no_gt_0'),
    sa.CheckConstraint('order_qty > 0', name='ck_order_line__order_qty_gt_0'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_line_id'),
    sa.UniqueConstraint('order_no', 'line_no', name='uq_order_line__order_no__line_no')
    )
    op.create_index('ix_order_line__due_date', 'order_line', ['due_date'], unique=False)
    op.create_index('ix_order_line__is_active', 'order_line', ['is_active'], unique=False)
    op.create_index('ix_order_line__order_date', 'order_line', ['order_date'], unique=False)
    op.create_index('ix_order_line__order_no', 'order_line', ['order_no'], unique=False)
    op.create_index('ix_order_line__partner_id', 'order_line', ['partner_id'], unique=False)
    op.create_index('ix_order_line__product_id', 'order_line', ['product_id'], unique=False)
    op.create_index('ix_order_line__status', 'order_line', ['status'], unique=False)
    op.create_table('outsource_work_group',
    sa.Column('outsource_work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('group_seq', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('sheet_qty', sa.BigInteger(), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sheet_cut_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('vendor_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_done_sheet_qty', sa.BigInteger(), nullable=True),
    sa.Column('outsource_processing_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('work_done_remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type IN ('CUT','PRINT','DIECUT')", name='ck_outsource_work_group__process_type'),
    sa.CheckConstraint("status IS NULL OR status IN ('VENDOR_RECEIVED','WORK_DONE','SHIPPED')", name='ck_outsource_work_group__status'),
    sa.CheckConstraint('outsource_processing_fee IS NULL OR outsource_processing_fee >= 0', name='ck_outsource_work_group__outsource_processing_fee_ge_0'),
    sa.CheckConstraint('sheet_cut_count > 0', name='ck_outsource_work_group__sheet_cut_count_gt_0'),
    sa.CheckConstraint('sheet_qty > 0', name='ck_outsource_work_group__sheet_qty_gt_0'),
    sa.CheckConstraint('work_done_sheet_qty IS NULL OR work_done_sheet_qty >= 0', name='ck_outsource_work_group__work_done_sheet_qty_ge_0'),
    sa.ForeignKeyConstraint(['outsource_work_instruction_id'], ['outsource_work_instruction.outsource_work_instruction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outsource_work_group_id')
    )
    op.create_index('ix_outsource_work_group__instruction_id', 'outsource_work_group', ['outsource_work_instruction_id'], unique=False)
    op.create_index('ix_outsource_work_group__process_type', 'outsource_work_group', ['process_type'], unique=False)
    op.create_table('outsource_work_instruction_file',
    sa.Column('outsource_work_instruction_file_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outsource_work_instruction_id'], ['outsource_work_instruction.outsource_work_instruction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outsource_work_instruction_file_id')
    )
    op.create_index('ix_outsource_work_instruction_file__instruction_id', 'outsource_work_instruction_file', ['outsource_work_instruction_id'], unique=False)
    op.create_table('lot',
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_no', sa.String(length=20), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_lot_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_qty', sa.BigInteger(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('material_lot_no', sa.String(length=100), nullable=True),
    sa.Column('material_used_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('material_sheet_count', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.CheckConstraint('lot_qty > 0', name='ck_lot__lot_qty_gt_0'),
    sa.CheckConstraint('material_sheet_count IS NULL OR material_sheet_count > 0', name='ck_lot__material_sheet_count_gt_0'),
    sa.CheckConstraint('material_used_qty IS NULL OR material_used_qty > 0', name='ck_lot__material_used_qty_gt_0'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.order_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_id'),
    sa.UniqueConstraint('lot_no')
    )
    op.create_index('ix_lot__created_date', 'lot', ['created_date'], unique=False)
    op.create_index('ix_lot__due_date', 'lot', ['due_date'], unique=False)
    op.create_index('ix_lot__lot_no', 'lot', ['lot_no'], unique=False)
    op.create_index('ix_lot__material_lot_no', 'lot', ['material_lot_no'], unique=False)
    op.create_index('ix_lot__order_line_id', 'lot', ['order_line_id'], unique=False)
    op.create_index('ix_lot__product_id', 'lot', ['product_id'], unique=False)
    op.create_table('outsource_purchase_order_group',
    sa.Column('outsource_purchase_order_group_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('item_seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vendor_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IS NULL OR status IN ('VENDOR_RECEIVED','WORK_DONE','SHIPPED')", name='ck_outsource_purchase_order_group__status'),
    sa.ForeignKeyConstraint(['outsource_purchase_order_id'], ['outsource_purchase_order.outsource_purchase_order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outsource_work_group_id'], ['outsource_work_group.outsource_work_group_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outsource_purchase_order_group_id')
    )
    op.create_index('ix_outsource_purchase_order_group__purchase_order_id', 'outsource_purchase_order_group', ['outsource_purchase_order_id'], unique=False)
    op.create_index('ix_outsource_purchase_order_group__status', 'outsource_purchase_order_group', ['status'], unique=False)
    op.create_index('ix_outsource_purchase_order_group__work_group_id', 'outsource_purchase_order_group', ['outsource_work_group_id'], unique=False)
    op.create_table('lot_step',
    sa.Column('lot_step_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('process_code', sa.String(length=30), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('WAITING','IN_PROGRESS','DONE','CANCELED')", name='ck_lot_step__status_enum'),
    sa.CheckConstraint('step_seq > 0', name='ck_lot_step__step_seq_gt_0'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_step_id'),
    sa.UniqueConstraint('lot_id', 'step_seq', name='uq_lot_step__lot_id__step_seq')
    )
    op.create_index('ix_lot_step__lot_id', 'lot_step', ['lot_id'], unique=False)
    op.create_index('ix_lot_step__process_id', 'lot_step', ['process_id'], unique=False)
    op.create_table('outsource_purchase_order_item',
    sa.Column('outsource_purchase_order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_instruction_id', sa.BigInteger(), nullable=True),
    sa.Column('item_seq', sa.Integer(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vendor_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_done_qty', sa.BigInteger(), nullable=True),
    sa.Column('bad_qty', sa.BigInteger(), nullable=True),
    sa.Column('work_done_remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IS NULL OR status IN ('VENDOR_RECEIVED','WORK_DONE','SHIPPED')", name='ck_outsource_purchase_order_item__status'),
    sa.CheckConstraint('bad_qty IS NULL OR bad_qty >= 0', name='ck_outsource_purchase_order_item__bad_qty_ge_0'),
    sa.CheckConstraint('qty > 0', name='ck_outsource_purchase_order_item__qty_gt_0'),
    sa.CheckConstraint('work_done_qty IS NULL OR work_done_qty >= 0', name='ck_outsource_purchase_order_item__work_done_qty_ge_0'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outsource_purchase_order_id'], ['outsource_purchase_order.outsource_purchase_order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outsource_purchase_order_item_id')
    )
    op.create_index('ix_outsource_purchase_order_item__lot_id', 'outsource_purchase_order_item', ['lot_id'], unique=False)
    op.create_index('ix_outsource_purchase_order_item__purchase_order_id', 'outsource_purchase_order_item', ['outsource_purchase_order_id'], unique=False)
    op.create_index('ix_outsource_purchase_order_item__status', 'outsource_purchase_order_item', ['status'], unique=False)
    op.create_table('outsource_work_group_item',
    sa.Column('outsource_work_group_item_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_group_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('cuts_per_sheet', sa.Integer(), nullable=False),
    sa.Column('expected_output_qty', sa.BigInteger(), nullable=True),
    sa.Column('actual_output_qty', sa.BigInteger(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_output_qty IS NULL OR actual_output_qty >= 0', name='ck_outsource_work_group_item__actual_output_qty_ge_0'),
    sa.CheckConstraint('cuts_per_sheet > 0', name='ck_outsource_work_group_item__cuts_per_sheet_gt_0'),
    sa.CheckConstraint('expected_output_qty IS NULL OR expected_output_qty >= 0', name='ck_outsource_work_group_item__expected_output_qty_ge_0'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outsource_work_group_id'], ['outsource_work_group.outsource_work_group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outsource_work_group_item_id')
    )
    op.create_index('ix_outsource_work_group_item__lot_id', 'outsource_work_group_item', ['lot_id'], unique=False)
    op.create_index('ix_outsource_work_group_item__work_group_id', 'outsource_work_group_item', ['outsource_work_group_id'], unique=False)
    op.create_table('outsource_work_instruction_item',
    sa.Column('outsource_work_instruction_item_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_instruction_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('process_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['outsource_work_instruction_id'], ['outsource_work_instruction.outsource_work_instruction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outsource_work_instruction_item_id'),
    sa.UniqueConstraint('process_type', 'lot_id', name='uq_outsource_work_instruction_item__process_type__lot_id')
    )
    op.create_index('ix_outsource_work_instruction_item__instruction_id', 'outsource_work_instruction_item', ['outsource_work_instruction_id'], unique=False)
    op.create_index('ix_outsource_work_instruction_item__lot_id', 'outsource_work_instruction_item', ['lot_id'], unique=False)
    op.create_table('inspection_schedule',
    sa.Column('inspection_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('outsource_work_group_id', sa.BigInteger(), nullable=True),
    sa.Column('outsource_work_group_item_id', sa.BigInteger(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('day_seq', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('WAITING','RECEIVED','IN_PROGRESS','PARTIAL_DONE','DONE','CANCELED')", name='ck_inspection_schedule__status'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outsource_work_group_id'], ['outsource_work_group.outsource_work_group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outsource_work_group_item_id'], ['outsource_work_group_item.outsource_work_group_item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inspection_schedule_id'),
    sa.UniqueConstraint('lot_id', 'inspection_date', name='uq_inspection_schedule__lot__date')
    )
    op.create_index('ix_inspection_schedule__inspection_date', 'inspection_schedule', ['inspection_date'], unique=False)
    op.create_index('ix_inspection_schedule__lot_id', 'inspection_schedule', ['lot_id'], unique=False)
    op.create_index('ix_inspection_schedule__outsource_work_group_id', 'inspection_schedule', ['outsource_work_group_id'], unique=False)
    op.create_index('ix_inspection_schedule__outsource_work_group_item_id', 'inspection_schedule', ['outsource_work_group_item_id'], unique=False)
    op.create_table('inspection_result',
    sa.Column('inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('good_qty', sa.Integer(), nullable=False),
    sa.Column('defect_ship_qty', sa.Integer(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('inspected_qty', sa.Integer(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('next_inspection_date', sa.Date(), nullable=True),
    sa.Column('partial_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defect_qty >= 0', name='ck_inspection_result__defect_qty'),
    sa.CheckConstraint('defect_ship_qty >= 0', name='ck_inspection_result__defect_ship_qty'),
    sa.CheckConstraint('good_qty >= 0', name='ck_inspection_result__good_qty'),
    sa.CheckConstraint('inspected_qty = good_qty + defect_ship_qty + defect_qty', name='ck_inspection_result__inspected_qty_calc_v2'),
    sa.ForeignKeyConstraint(['inspection_schedule_id'], ['inspection_schedule.inspection_schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_result_id'),
    sa.UniqueConstraint('inspection_schedule_id', name='uq_inspection_result__schedule')
    )
    op.create_index('ix_inspection_result__schedule', 'inspection_result', ['inspection_schedule_id'], unique=False)
    op.create_table('inspection_certificate',
    sa.Column('inspection_certificate_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('basis_inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basis_inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inspection_certificate_id'),
    sa.UniqueConstraint('lot_id', name='uq_inspection_certificate__lot')
    )
    op.create_index('ix_inspection_certificate__issued_at', 'inspection_certificate', ['issued_at'], unique=False)
    op.create_table('inspection_defect',
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_type_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IN ('SHIP_AS_IS','NOT_SHIPPABLE')", name='ck_inspection_defect__disposition'),
    sa.CheckConstraint('defect_qty >= 0', name='ck_inspection_defect__defect_qty'),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_type.defect_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_id')
    )
    op.create_index('ix_inspection_defect__defect_type_id', 'inspection_defect', ['defect_type_id'], unique=False)
    op.create_index('ix_inspection_defect__inspection_result_id', 'inspection_defect', ['inspection_result_id'], unique=False)
    op.create_table('inspection_defect_attachment',
    sa.Column('inspection_defect_attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('file_uri', sa.String(length=600), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_defect_id'], ['inspection_defect.inspection_defect_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_attachment_id')
    )
    op.create_index('ix_inspection_defect_attachment__inspection_defect_id', 'inspection_defect_attachment', ['inspection_defect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_defect_attachment__inspection_defect_id', table_name='inspection_defect_attachment')
    op.drop_table('inspection_defect_attachment')
    op.drop_index('ix_inspection_defect__inspection_result_id', table_name='inspection_defect')
    op.drop_index('ix_inspection_defect__defect_type_id', table_name='inspection_defect')
    op.drop_table('inspection_defect')
    op.drop_index('ix_inspection_certificate__issued_at', table_name='inspection_certificate')
    op.drop_table('inspection_certificate')
    op.drop_index('ix_inspection_result__schedule', table_name='inspection_result')
    op.drop_table('inspection_result')
    op.drop_index('ix_inspection_schedule__outsource_work_group_item_id', table_name='inspection_schedule')
    op.drop_index('ix_inspection_schedule__outsource_work_group_id', table_name='inspection_schedule')
    op.drop_index('ix_inspection_schedule__lot_id', table_name='inspection_schedule')
    op.drop_index('ix_inspection_schedule__inspection_date', table_name='inspection_schedule')
    op.drop_table('inspection_schedule')
    op.drop_index('ix_outsource_work_instruction_item__lot_id', table_name='outsource_work_instruction_item')
    op.drop_index('ix_outsource_work_instruction_item__instruction_id', table_name='outsource_work_instruction_item')
    op.drop_table('outsource_work_instruction_item')
    op.drop_index('ix_outsource_work_group_item__work_group_id', table_name='outsource_work_group_item')
    op.drop_index('ix_outsource_work_group_item__lot_id', table_name='outsource_work_group_item')
    op.drop_table('outsource_work_group_item')
    op.drop_index('ix_outsource_purchase_order_item__status', table_name='outsource_purchase_order_item')
    op.drop_index('ix_outsource_purchase_order_item__purchase_order_id', table_name='outsource_purchase_order_item')
    op.drop_index('ix_outsource_purchase_order_item__lot_id', table_name='outsource_purchase_order_item')
    op.drop_table('outsource_purchase_order_item')
    op.drop_index('ix_lot_step__process_id', table_name='lot_step')
    op.drop_index('ix_lot_step__lot_id', table_name='lot_step')
    op.drop_table('lot_step')
    op.drop_index('ix_outsource_purchase_order_group__work_group_id', table_name='outsource_purchase_order_group')
    op.drop_index('ix_outsource_purchase_order_group__status', table_name='outsource_purchase_order_group')
    op.drop_index('ix_outsource_purchase_order_group__purchase_order_id', table_name='outsource_purchase_order_group')
    op.drop_table('outsource_purchase_order_group')
    op.drop_index('ix_lot__product_id', table_name='lot')
    op.drop_index('ix_lot__order_line_id', table_name='lot')
    op.drop_index('ix_lot__material_lot_no', table_name='lot')
    op.drop_index('ix_lot__lot_no', table_name='lot')
    op.drop_index('ix_lot__due_date', table_name='lot')
    op.drop_index('ix_lot__created_date', table_name='lot')
    op.drop_table('lot')
    op.drop_index('ix_outsource_work_instruction_file__instruction_id', table_name='outsource_work_instruction_file')
    op.drop_table('outsource_work_instruction_file')
    op.drop_index('ix_outsource_work_group__process_type', table_name='outsource_work_group')
    op.drop_index('ix_outsource_work_group__instruction_id', table_name='outsource_work_group')
    op.drop_table('outsource_work_group')
    op.drop_index('ix_order_line__status', table_name='order_line')
    op.drop_index('ix_order_line__product_id', table_name='order_line')
    op.drop_index('ix_order_line__partner_id', table_name='order_line')
    op.drop_index('ix_order_line__order_no', table_name='order_line')
    op.drop_index('ix_order_line__order_date', table_name='order_line')
    op.drop_index('ix_order_line__is_active', table_name='order_line')
    op.drop_index('ix_order_line__due_date', table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_routing_template_step_routing_template_id'), table_name='routing_template_step')
    op.drop_index(op.f('ix_routing_template_step_process_id'), table_name='routing_template_step')
    op.drop_table('routing_template_step')
    op.drop_index('ix_product__is_active', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_outsource_work_instruction__process_type', table_name='outsource_work_instruction')
    op.drop_index('ix_outsource_work_instruction__partner_id', table_name='outsource_work_instruction')
    op.drop_index('ix_outsource_work_instruction__instruction_date', table_name='outsource_work_instruction')
    op.drop_table('outsource_work_instruction')
    op.drop_index('ix_outsource_purchase_order__purchase_order_no', table_name='outsource_purchase_order')
    op.drop_index('ix_outsource_purchase_order__purchase_order_date', table_name='outsource_purchase_order')
    op.drop_index('ix_outsource_purchase_order__process_type', table_name='outsource_purchase_order')
    op.drop_index('ix_outsource_purchase_order__outsource_partner_id', table_name='outsource_purchase_order')
    op.drop_index('ix_outsource_purchase_order__inbound_partner_id', table_name='outsource_purchase_order')
    op.drop_table('outsource_purchase_order')
    op.drop_index('ix_drawing_revision_file__revision_id', table_name='drawing_revision_file')
    op.drop_index('ix_drawing_revision_file__file_kind', table_name='drawing_revision_file')
    op.drop_table('drawing_revision_file')
    op.drop_index(op.f('ix_routing_template_template_code'), table_name='routing_template')
    op.drop_table('routing_template')
    op.drop_index(op.f('ix_process_process_code'), table_name='process')
    op.drop_table('process')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_table('partner')
    op.drop_index('ix_drawing_revision__drawing_id', table_name='drawing_revision')
    op.drop_table('drawing_revision')
    op.drop_index('ix_drawing__is_active', table_name='drawing')
    op.drop_table('drawing')
    op.drop_index(op.f('ix_defect_type_name'), table_name='defect_type')
    op.drop_index(op.f('ix_defect_type_code'), table_name='defect_type')
    op.drop_table('defect_type')
    # ### end Alembic commands ###
