"""baseline v1

Revision ID: d191e7ff2e9a
Revises: 
Create Date: 2026-02-25 10:19:01.743115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd191e7ff2e9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_type',
    sa.Column('defect_type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('defect_type_id')
    )
    op.create_index(op.f('ix_defect_type_code'), 'defect_type', ['code'], unique=True)
    op.create_index(op.f('ix_defect_type_name'), 'defect_type', ['name'], unique=False)
    op.create_table('drawing',
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('drawing_no', sa.String(length=60), nullable=False),
    sa.Column('current_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('drawing_id'),
    sa.UniqueConstraint('drawing_no', name='uq_drawing__drawing_no')
    )
    op.create_index('ix_drawing__is_active', 'drawing', ['is_active'], unique=False)
    op.create_table('drawing_revision',
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('rev_no', sa.String(length=20), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('drawing_id', 'rev_no', name='uq_drawing_revision__drawing_id__rev_no')
    )
    op.create_foreign_key("fk_drawing__current_revision_id", "drawing", "drawing_revision", ["current_revision_id"], ["revision_id"], ondelete="SET NULL")
    op.create_index('ix_drawing_revision__drawing_id', 'drawing_revision', ['drawing_id'], unique=False)
    op.create_table('partner',
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('partner_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_no', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('business_no')
    )
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=False)
    op.create_table('process',
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_index(op.f('ix_process_process_code'), 'process', ['process_code'], unique=True)
    op.create_table('routing_template',
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('routing_template_id')
    )
    op.create_index(op.f('ix_routing_template_template_code'), 'routing_template', ['template_code'], unique=True)
    op.create_table('product',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=60), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('drawing_id', sa.BigInteger(), nullable=False),
    sa.Column('panel_width_mm', sa.Integer(), nullable=True),
    sa.Column('panel_length_mm', sa.Integer(), nullable=True),
    sa.Column('product_spec', sa.String(length=100), nullable=True),
    sa.Column('cut_qty_per_panel', sa.Integer(), nullable=True),
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('drawing_id', name='uq_product__drawing_id'),
    sa.UniqueConstraint('product_code', name='uq_product__product_code')
    )
    op.create_index('ix_product__is_active', 'product', ['is_active'], unique=False)
    op.create_table('routing_template_step',
    sa.Column('routing_template_step_id', sa.BigInteger(), nullable=False),
    sa.Column('routing_template_id', sa.BigInteger(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('default_process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("default_process_type IN ('OUTSOURCE','INTERNAL')", name='ck_routing_template_step_default_process_type'),
    sa.CheckConstraint('step_seq > 0', name='ck_routing_template_step_seq_gt_0'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routing_template_step_id'),
    sa.UniqueConstraint('routing_template_id', 'step_seq', name='uq_routing_template_step_seq')
    )
    op.create_index(op.f('ix_routing_template_step_process_id'), 'routing_template_step', ['process_id'], unique=False)
    op.create_index(op.f('ix_routing_template_step_routing_template_id'), 'routing_template_step', ['routing_template_id'], unique=False)
    op.create_table('order_line',
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('customer_po', sa.String(length=60), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED','DONE','CANCELED')", name='ck_order_line__status_enum'),
    sa.CheckConstraint('line_no > 0', name='ck_order_line__line_no_gt_0'),
    sa.CheckConstraint('order_qty > 0', name='ck_order_line__order_qty_gt_0'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_line_id'),
    sa.UniqueConstraint('order_no', 'line_no', name='uq_order_line__order_no__line_no')
    )
    op.create_index('ix_order_line__due_date', 'order_line', ['due_date'], unique=False)
    op.create_index('ix_order_line__is_active', 'order_line', ['is_active'], unique=False)
    op.create_index('ix_order_line__order_date', 'order_line', ['order_date'], unique=False)
    op.create_index('ix_order_line__order_no', 'order_line', ['order_no'], unique=False)
    op.create_index('ix_order_line__partner_id', 'order_line', ['partner_id'], unique=False)
    op.create_index('ix_order_line__product_id', 'order_line', ['product_id'], unique=False)
    op.create_index('ix_order_line__status', 'order_line', ['status'], unique=False)
    op.create_table('lot',
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_no', sa.String(length=20), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_lot_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_qty', sa.BigInteger(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.CheckConstraint('lot_qty > 0', name='ck_lot__lot_qty_gt_0'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.order_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_id'),
    sa.UniqueConstraint('lot_no')
    )
    op.create_index('ix_lot__created_date', 'lot', ['created_date'], unique=False)
    op.create_index('ix_lot__due_date', 'lot', ['due_date'], unique=False)
    op.create_index('ix_lot__lot_no', 'lot', ['lot_no'], unique=False)
    op.create_index('ix_lot__order_line_id', 'lot', ['order_line_id'], unique=False)
    op.create_index('ix_lot__product_id', 'lot', ['product_id'], unique=False)
    op.create_table('inspection_schedule',
    sa.Column('inspection_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('day_seq', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('WAITING','RECEIVED','IN_PROGRESS','PARTIAL_DONE','DONE','CANCELED')", name='ck_inspection_schedule__status'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_schedule_id'),
    sa.UniqueConstraint('lot_id', 'inspection_date', name='uq_inspection_schedule__lot__date')
    )
    op.create_index('ix_inspection_schedule__inspection_date', 'inspection_schedule', ['inspection_date'], unique=False)
    op.create_index('ix_inspection_schedule__lot_id', 'inspection_schedule', ['lot_id'], unique=False)
    op.create_table('lot_step',
    sa.Column('lot_step_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('process_code', sa.String(length=30), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('WAITING','IN_PROGRESS','DONE','CANCELED')", name='ck_lot_step__status_enum'),
    sa.CheckConstraint('step_seq > 0', name='ck_lot_step__step_seq_gt_0'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_step_id'),
    sa.UniqueConstraint('lot_id', 'step_seq', name='uq_lot_step__lot_id__step_seq')
    )
    op.create_index("ux_lot_step__one_in_progress_per_lot", "lot_step", ["lot_id"], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_index('ix_lot_step__lot_id', 'lot_step', ['lot_id'], unique=False)
    op.create_index('ix_lot_step__process_id', 'lot_step', ['process_id'], unique=False)
    op.create_table('inspection_result',
    sa.Column('inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('good_qty', sa.Integer(), nullable=False),
    sa.Column('defect_ship_qty', sa.Integer(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('inspected_qty', sa.Integer(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('next_inspection_date', sa.Date(), nullable=True),
    sa.Column('partial_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defect_qty >= 0', name='ck_inspection_result__defect_qty'),
    sa.CheckConstraint('defect_ship_qty >= 0', name='ck_inspection_result__defect_ship_qty'),
    sa.CheckConstraint('good_qty >= 0', name='ck_inspection_result__good_qty'),
    sa.CheckConstraint('inspected_qty = good_qty + defect_ship_qty + defect_qty', name='ck_inspection_result__inspected_qty_calc_v2'),
    sa.ForeignKeyConstraint(['inspection_schedule_id'], ['inspection_schedule.inspection_schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_result_id'),
    sa.UniqueConstraint('inspection_schedule_id', name='uq_inspection_result__schedule')
    )
    op.create_index('ix_inspection_result__schedule', 'inspection_result', ['inspection_schedule_id'], unique=False)
    op.create_table('inspection_certificate',
    sa.Column('inspection_certificate_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('basis_inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basis_inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inspection_certificate_id'),
    sa.UniqueConstraint('lot_id', name='uq_inspection_certificate__lot')
    )
    op.create_index('ix_inspection_certificate__issued_at', 'inspection_certificate', ['issued_at'], unique=False)
    op.create_table('inspection_defect',
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_type_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IN ('SHIP_AS_IS','NOT_SHIPPABLE')", name='ck_inspection_defect__disposition'),
    sa.CheckConstraint('defect_qty >= 0', name='ck_inspection_defect__defect_qty'),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_type.defect_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_id')
    )
    op.create_index('ix_inspection_defect__defect_type_id', 'inspection_defect', ['defect_type_id'], unique=False)
    op.create_index('ix_inspection_defect__inspection_result_id', 'inspection_defect', ['inspection_result_id'], unique=False)
    op.create_table('inspection_defect_attachment',
    sa.Column('inspection_defect_attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('file_uri', sa.String(length=600), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_defect_id'], ['inspection_defect.inspection_defect_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_attachment_id')
    )
    op.create_index('ix_inspection_defect_attachment__inspection_defect_id', 'inspection_defect_attachment', ['inspection_defect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_defect_attachment__inspection_defect_id', table_name='inspection_defect_attachment')
    op.drop_table('inspection_defect_attachment')
    op.drop_index('ix_inspection_defect__inspection_result_id', table_name='inspection_defect')
    op.drop_index('ix_inspection_defect__defect_type_id', table_name='inspection_defect')
    op.drop_table('inspection_defect')
    op.drop_index('ix_inspection_certificate__issued_at', table_name='inspection_certificate')
    op.drop_table('inspection_certificate')
    op.drop_index('ix_inspection_result__schedule', table_name='inspection_result')
    op.drop_table('inspection_result')
    op.drop_index('ix_lot_step__process_id', table_name='lot_step')
    op.drop_index('ix_lot_step__lot_id', table_name='lot_step')
    op.drop_table('lot_step')
    op.drop_index('ix_inspection_schedule__lot_id', table_name='inspection_schedule')
    op.drop_index('ix_inspection_schedule__inspection_date', table_name='inspection_schedule')
    op.drop_table('inspection_schedule')
    op.drop_index('ix_lot__product_id', table_name='lot')
    op.drop_index('ix_lot__order_line_id', table_name='lot')
    op.drop_index('ix_lot__lot_no', table_name='lot')
    op.drop_index('ix_lot__due_date', table_name='lot')
    op.drop_index('ix_lot__created_date', table_name='lot')
    op.drop_table('lot')
    op.drop_index('ix_order_line__status', table_name='order_line')
    op.drop_index('ix_order_line__product_id', table_name='order_line')
    op.drop_index('ix_order_line__partner_id', table_name='order_line')
    op.drop_index('ix_order_line__order_no', table_name='order_line')
    op.drop_index('ix_order_line__order_date', table_name='order_line')
    op.drop_index('ix_order_line__is_active', table_name='order_line')
    op.drop_index('ix_order_line__due_date', table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_routing_template_step_routing_template_id'), table_name='routing_template_step')
    op.drop_index(op.f('ix_routing_template_step_process_id'), table_name='routing_template_step')
    op.drop_table('routing_template_step')
    op.drop_index('ix_product__is_active', table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_routing_template_template_code'), table_name='routing_template')
    op.drop_table('routing_template')
    op.drop_index(op.f('ix_process_process_code'), table_name='process')
    op.drop_table('process')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_table('partner')
    op.drop_index('ix_drawing_revision__drawing_id', table_name='drawing_revision')
    op.drop_table('drawing_revision')
    op.drop_index('ix_drawing__is_active', table_name='drawing')
    op.drop_constraint("fk_drawing__current_revision_id", "drawing", type_="foreignkey")
    op.drop_table('drawing')
    op.drop_index(op.f('ix_defect_type_name'), table_name='defect_type')
    op.drop_index(op.f('ix_defect_type_code'), table_name='defect_type')
    op.drop_table('defect_type')

    # ### end Alembic commands ###
