"""create inspection_defect

Revision ID: 194301b9e9e1
Revises: dec0356d97e1
Create Date: 2026-02-09 15:27:17.910969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194301b9e9e1'
down_revision: Union[str, Sequence[str], None] = 'dec0356d97e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_defect',
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_type_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('defect_qty >= 0', name='ck_inspection_defect__defect_qty'),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_type.defect_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_id')
    )
    op.create_index('ix_inspection_defect__defect_type_id', 'inspection_defect', ['defect_type_id'], unique=False)
    op.create_index('ix_inspection_defect__inspection_result_id', 'inspection_defect', ['inspection_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_defect__inspection_result_id', table_name='inspection_defect')
    op.drop_index('ix_inspection_defect__defect_type_id', table_name='inspection_defect')
    op.drop_table('inspection_defect')
    # ### end Alembic commands ###
