"""add drawing current_revision fk

Revision ID: 19bf909c6dbc
Revises: c2e4205a003f
Create Date: 2026-02-05 16:02:03.767631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bf909c6dbc'
down_revision: Union[str, Sequence[str], None] = 'c2e4205a003f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'drawing', 'drawing_revision', ['current_revision_id'], ['revision_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drawing', type_='foreignkey')
    # ### end Alembic commands ###
