"""create routing_template

Revision ID: 2d51fc8b8a84
Revises: 66e85677bbc5
Create Date: 2026-02-05 14:28:00.648289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d51fc8b8a84'
down_revision: Union[str, Sequence[str], None] = '66e85677bbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_template',
    sa.Column('routing_template_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('routing_template_id')
    )
    op.create_index(op.f('ix_routing_template_template_code'), 'routing_template', ['template_code'], unique=True)
    op.create_table('routing_template_step',
    sa.Column('routing_template_step_id', sa.Integer(), nullable=False),
    sa.Column('routing_template_id', sa.Integer(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('default_process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("default_process_type IN ('OUTSOURCE','INTERNAL')", name='ck_routing_template_step_default_process_type'),
    sa.CheckConstraint('step_seq > 0', name='ck_routing_template_step_seq_gt_0'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routing_template_step_id'),
    sa.UniqueConstraint('routing_template_id', 'step_seq', name='uq_routing_template_step_seq')
    )
    op.create_index(op.f('ix_routing_template_step_process_id'), 'routing_template_step', ['process_id'], unique=False)
    op.create_index(op.f('ix_routing_template_step_routing_template_id'), 'routing_template_step', ['routing_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_template_step_routing_template_id'), table_name='routing_template_step')
    op.drop_index(op.f('ix_routing_template_step_process_id'), table_name='routing_template_step')
    op.drop_table('routing_template_step')
    op.drop_index(op.f('ix_routing_template_template_code'), table_name='routing_template')
    op.drop_table('routing_template')
    # ### end Alembic commands ###
