"""create order_line

Revision ID: 55820111efe6
Revises: 7dc9af5c93a2
Create Date: 2026-02-05 17:19:43.042901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55820111efe6'
down_revision: Union[str, Sequence[str], None] = '7dc9af5c93a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_line',
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('customer_po', sa.String(length=60), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_no > 0', name='ck_order_line__line_no_gt_0'),
    sa.CheckConstraint('order_qty > 0', name='ck_order_line__order_qty_gt_0'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partner_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_line_id'),
    sa.UniqueConstraint('order_no', 'line_no', name='uq_order_line__order_no__line_no')
    )
    op.create_index('ix_order_line__due_date', 'order_line', ['due_date'], unique=False)
    op.create_index('ix_order_line__order_date', 'order_line', ['order_date'], unique=False)
    op.create_index('ix_order_line__order_no', 'order_line', ['order_no'], unique=False)
    op.create_index('ix_order_line__partner_id', 'order_line', ['partner_id'], unique=False)
    op.create_index('ix_order_line__product_id', 'order_line', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_line__product_id', table_name='order_line')
    op.drop_index('ix_order_line__partner_id', table_name='order_line')
    op.drop_index('ix_order_line__order_no', table_name='order_line')
    op.drop_index('ix_order_line__order_date', table_name='order_line')
    op.drop_index('ix_order_line__due_date', table_name='order_line')
    op.drop_table('order_line')
    # ### end Alembic commands ###
