"""create inspection_certificate

Revision ID: 565c16e800ec
Revises: 6c5c04904b3b
Create Date: 2026-02-09 15:37:35.447886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565c16e800ec'
down_revision: Union[str, Sequence[str], None] = '6c5c04904b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_certificate',
    sa.Column('inspection_certificate_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('basis_inspection_result_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basis_inspection_result_id'], ['inspection_result.inspection_result_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inspection_certificate_id'),
    sa.UniqueConstraint('lot_id', name='uq_inspection_certificate__lot')
    )
    op.create_index('ix_inspection_certificate__issued_at', 'inspection_certificate', ['issued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_certificate__issued_at', table_name='inspection_certificate')
    op.drop_table('inspection_certificate')
    # ### end Alembic commands ###
