"""create inspection_schedule

Revision ID: 56a63bdd5c8d
Revises: 35e5bd18d677
Create Date: 2026-02-09 15:19:36.307075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a63bdd5c8d'
down_revision: Union[str, Sequence[str], None] = '35e5bd18d677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_schedule',
    sa.Column('inspection_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('day_seq', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('WAITING','RECEIVED','IN_PROGRESS','PARTIAL_DONE','DONE','CANCELED')", name='ck_inspection_schedule__status'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_schedule_id'),
    sa.UniqueConstraint('lot_id', 'inspection_date', name='uq_inspection_schedule__lot__date')
    )
    op.create_index('ix_inspection_schedule__inspection_date', 'inspection_schedule', ['inspection_date'], unique=False)
    op.create_index('ix_inspection_schedule__lot_id', 'inspection_schedule', ['lot_id'], unique=False)
    op.drop_index(op.f('ux_lot_step__one_in_progress_per_lot'), table_name='lot_step', postgresql_where="((status)::text = 'IN_PROGRESS'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_lot_step__one_in_progress_per_lot'), 'lot_step', ['lot_id'], unique=True, postgresql_where="((status)::text = 'IN_PROGRESS'::text)")
    op.drop_index('ix_inspection_schedule__lot_id', table_name='inspection_schedule')
    op.drop_index('ix_inspection_schedule__inspection_date', table_name='inspection_schedule')
    op.drop_table('inspection_schedule')
    # ### end Alembic commands ###
