"""create process

Revision ID: 66e85677bbc5
Revises: 99e81314e4ff
Create Date: 2026-02-05 14:15:51.759781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e85677bbc5'
down_revision: Union[str, Sequence[str], None] = '99e81314e4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_index(op.f('ix_process_process_code'), 'process', ['process_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_process_code'), table_name='process')
    op.drop_table('process')
    # ### end Alembic commands ###
