"""create inspection_defect_attachment

Revision ID: 6c5c04904b3b
Revises: 194301b9e9e1
Create Date: 2026-02-09 15:29:26.811414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5c04904b3b'
down_revision: Union[str, Sequence[str], None] = '194301b9e9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_defect_attachment',
    sa.Column('inspection_defect_attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_defect_id', sa.BigInteger(), nullable=False),
    sa.Column('file_uri', sa.String(length=600), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_defect_id'], ['inspection_defect.inspection_defect_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_defect_attachment_id')
    )
    op.create_index('ix_inspection_defect_attachment__inspection_defect_id', 'inspection_defect_attachment', ['inspection_defect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_defect_attachment__inspection_defect_id', table_name='inspection_defect_attachment')
    op.drop_table('inspection_defect_attachment')
    # ### end Alembic commands ###
