"""drawing required 1to1 and auto current

Revision ID: 7dc9af5c93a2
Revises: ab39dca98c7b
Create Date: 2026-02-05 17:07:37.814238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc9af5c93a2'
down_revision: Union[str, Sequence[str], None] = 'ab39dca98c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('drawing', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('drawing', 'drawing_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('drawing', 'drawing_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('drawing', 'current_revision_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_drawing_drawing_no'), table_name='drawing')
    op.create_index('ix_drawing__is_active', 'drawing', ['is_active'], unique=False)
    op.create_unique_constraint('uq_drawing__drawing_no', 'drawing', ['drawing_no'])
    op.drop_constraint(op.f('drawing_current_revision_id_fkey'), 'drawing', type_='foreignkey')
    op.create_foreign_key(None, 'drawing', 'drawing_revision', ['current_revision_id'], ['revision_id'], ondelete='SET NULL')
    op.add_column('drawing_revision', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('drawing_revision', 'revision_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('drawing_revision', 'drawing_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('drawing_revision', 'rev_no',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_drawing_revision_drawing_id'), table_name='drawing_revision')
    op.create_index('ix_drawing_revision__drawing_id', 'drawing_revision', ['drawing_id'], unique=False)
    op.create_unique_constraint('uq_drawing_revision__drawing_id__rev_no', 'drawing_revision', ['drawing_id', 'rev_no'])
    op.add_column('product', sa.Column('memo', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('product', 'product_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('product', 'product_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('product', 'uom',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('product', 'drawing_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('product', 'routing_template_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_product_code'), table_name='product')
    op.drop_index(op.f('ix_product_routing_template_id'), table_name='product')
    op.create_index('ix_product__is_active', 'product', ['is_active'], unique=False)
    op.create_unique_constraint('uq_product__drawing_id', 'product', ['drawing_id'])
    op.create_unique_constraint('uq_product__product_code', 'product', ['product_code'])
    op.drop_constraint(op.f('product_routing_template_id_fkey'), 'product', type_='foreignkey')
    op.drop_constraint(op.f('product_drawing_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'drawing', ['drawing_id'], ['drawing_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'product', 'routing_template', ['routing_template_id'], ['routing_template_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_drawing_id_fkey'), 'product', 'drawing', ['drawing_id'], ['drawing_id'])
    op.create_foreign_key(op.f('product_routing_template_id_fkey'), 'product', 'routing_template', ['routing_template_id'], ['routing_template_id'])
    op.drop_constraint('uq_product__product_code', 'product', type_='unique')
    op.drop_constraint('uq_product__drawing_id', 'product', type_='unique')
    op.drop_index('ix_product__is_active', table_name='product')
    op.create_index(op.f('ix_product_routing_template_id'), 'product', ['routing_template_id'], unique=False)
    op.create_index(op.f('ix_product_product_code'), 'product', ['product_code'], unique=True)
    op.alter_column('product', 'routing_template_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('product', 'drawing_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'uom',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('product', 'product_code',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('product', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'memo')
    op.drop_constraint('uq_drawing_revision__drawing_id__rev_no', 'drawing_revision', type_='unique')
    op.drop_index('ix_drawing_revision__drawing_id', table_name='drawing_revision')
    op.create_index(op.f('ix_drawing_revision_drawing_id'), 'drawing_revision', ['drawing_id'], unique=False)
    op.alter_column('drawing_revision', 'rev_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('drawing_revision', 'drawing_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('drawing_revision', 'revision_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('drawing_revision', 'created_at')
    op.drop_constraint(None, 'drawing', type_='foreignkey')
    op.create_foreign_key(op.f('drawing_current_revision_id_fkey'), 'drawing', 'drawing_revision', ['current_revision_id'], ['revision_id'])
    op.drop_constraint('uq_drawing__drawing_no', 'drawing', type_='unique')
    op.drop_index('ix_drawing__is_active', table_name='drawing')
    op.create_index(op.f('ix_drawing_drawing_no'), 'drawing', ['drawing_no'], unique=True)
    op.alter_column('drawing', 'current_revision_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('drawing', 'drawing_no',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('drawing', 'drawing_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('drawing', 'updated_at')
    op.drop_column('drawing', 'created_at')
    # ### end Alembic commands ###
