"""create lot and lot_step

Revision ID: 97821b941323
Revises: 55820111efe6
Create Date: 2026-02-09 14:49:24.651084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97821b941323'
down_revision: Union[str, Sequence[str], None] = '55820111efe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_no', sa.String(length=20), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_lot_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_qty', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lot_qty > 0', name='ck_lot__lot_qty_gt_0'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.order_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_id'),
    sa.UniqueConstraint('lot_no')
    )
    op.create_index('ix_lot__created_date', 'lot', ['created_date'], unique=False)
    op.create_index('ix_lot__lot_no', 'lot', ['lot_no'], unique=False)
    op.create_index('ix_lot__order_line_id', 'lot', ['order_line_id'], unique=False)
    op.create_index('ix_lot__product_id', 'lot', ['product_id'], unique=False)
    op.create_table('lot_step',
    sa.Column('lot_step_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('step_seq', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.BigInteger(), nullable=False),
    sa.Column('process_code', sa.String(length=30), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('WAITING','IN_PROGRESS','DONE','CANCELED')", name='ck_lot_step__status_enum'),
    sa.CheckConstraint('step_seq > 0', name='ck_lot_step__step_seq_gt_0'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['process.process_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('lot_step_id'),
    sa.UniqueConstraint('lot_id', 'step_seq', name='uq_lot_step__lot_id__step_seq')
    )
    op.create_index('ix_lot_step__lot_id', 'lot_step', ['lot_id'], unique=False)
    op.create_index('ix_lot_step__process_id', 'lot_step', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lot_step__process_id', table_name='lot_step')
    op.drop_index('ix_lot_step__lot_id', table_name='lot_step')
    op.drop_table('lot_step')
    op.drop_index('ix_lot__product_id', table_name='lot')
    op.drop_index('ix_lot__order_line_id', table_name='lot')
    op.drop_index('ix_lot__lot_no', table_name='lot')
    op.drop_index('ix_lot__created_date', table_name='lot')
    op.drop_table('lot')
    # ### end Alembic commands ###
