"""create defect_type

Revision ID: ab39dca98c7b
Revises: f4cbe1701a37
Create Date: 2026-02-05 16:43:27.382579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab39dca98c7b'
down_revision: Union[str, Sequence[str], None] = 'f4cbe1701a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_type',
    sa.Column('defect_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('defect_type_id')
    )
    op.create_index(op.f('ix_defect_type_code'), 'defect_type', ['code'], unique=True)
    op.create_index(op.f('ix_defect_type_name'), 'defect_type', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defect_type_name'), table_name='defect_type')
    op.drop_index(op.f('ix_defect_type_code'), table_name='defect_type')
    op.drop_table('defect_type')
    # ### end Alembic commands ###
