"""create drawing tables

Revision ID: c2e4205a003f
Revises: 2d51fc8b8a84
Create Date: 2026-02-05 15:49:48.121181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e4205a003f'
down_revision: Union[str, Sequence[str], None] = '2d51fc8b8a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing',
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('drawing_no', sa.String(length=50), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('drawing_id')
    )
    op.create_index(op.f('ix_drawing_drawing_no'), 'drawing', ['drawing_no'], unique=True)
    op.create_table('drawing_revision',
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('rev_no', sa.String(length=10), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_drawing_revision_drawing_id'), 'drawing_revision', ['drawing_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=True),
    sa.Column('panel_width_mm', sa.Integer(), nullable=True),
    sa.Column('panel_length_mm', sa.Integer(), nullable=True),
    sa.Column('product_spec', sa.String(length=100), nullable=True),
    sa.Column('cut_qty_per_panel', sa.Integer(), nullable=True),
    sa.Column('routing_template_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawing.drawing_id'], ),
    sa.ForeignKeyConstraint(['routing_template_id'], ['routing_template.routing_template_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_code'), 'product', ['product_code'], unique=True)
    op.create_index(op.f('ix_product_routing_template_id'), 'product', ['routing_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_routing_template_id'), table_name='product')
    op.drop_index(op.f('ix_product_product_code'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_drawing_revision_drawing_id'), table_name='drawing_revision')
    op.drop_table('drawing_revision')
    op.drop_index(op.f('ix_drawing_drawing_no'), table_name='drawing')
    op.drop_table('drawing')
    # ### end Alembic commands ###
