"""add index to partner name

Revision ID: f4cbe1701a37
Revises: 5bc9a254a56f
Create Date: 2026-02-05 16:29:15.850719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cbe1701a37'
down_revision: Union[str, Sequence[str], None] = '5bc9a254a56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    # ### end Alembic commands ###
